version: '3.8'

volumes:
  ride-api:
  rabbitmq-ride:
  ride-mongodb:
  
services:
  ride-api:
    image: postgres
    container_name: ride-api
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'app'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - ./init/:/docker-entrypoint-initdb.d
      - ride-api:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbit-mq:
    image: rabbitmq:3.8-management
    container_name: rabbit-mq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: 'app'
      RABBITMQ_DEFAULT_PASS: '123456'
    volumes:
      - rabbitmq-ride:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  mongo: 
    container_name: node-ride-api
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - ride-mongodb:/data/db
    ports:
      - 27017:27017